version: "3"

services:
  ### Kafka
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  ### Warehouse
  warehouse:
    image: ghcr.io/msc-in-software-engineering/python_warehouse_pub_sub:latest
    environment:
      - KAFKA_BROKER_ADDRESS=kafka
    depends_on:
      - kafka
      - supply-chain-management-database

  ### SCM
  supply-chain-management-database:
    image: ghcr.io/msc-in-software-engineering/supply_chain_management_database:latest
    ports:
      - "5432:5432"

  warehouse-system:
    image: ghcr.io/msc-in-software-engineering/warehouse_system:latest
    environment:
      - KAFKA_BROKER_ADDRESS=kafka
    depends_on:
      - kafka

  customer-service:
    image: ghcr.io/msc-in-software-engineering/customer_service:latest
    env_file:
      - ./CustomerService/.env
    depends_on:
      - supply-chain-management-database

  ### PMS
  production-management-system:
    build:
      context: ghcr.io/msc-in-software-engineering/production_management_system:latest
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER_ADDRESS=kafka
    depends_on:
      - kafka
      - supply-chain-management-database
  
  ### MQTT Mediator
  mqtt-mediator:
    image: ghcr.io/msc-in-software-engineering/mqtt_mediator:latest
    environment:
      - KAFKA_BROKER_ADDRESS=kafka
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - kafka
    restart: on-failure

  ### Production floor
  iot:
    image: ghcr.io/msc-in-software-engineering/python_iot_pub:latest
    environment:
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - production-broker

  conveyor-belts:
    image: ghcr.io/msc-in-software-engineering/python_conveyor_belts_pub:latest
    environment:
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - production-broker

  robotics:
    image: ghcr.io/msc-in-software-engineering/python_robotics_pub:latest
    environment:
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - production-broker
      
  ### Metrics analysis
  metrics-analysis:
    image: ghcr.io/msc-in-software-engineering/metrics_analysis:latest
    depends_on:
      - kafka
      - production-broker

  # Mosquitto
  production-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  kafka_data:
    driver: local
