version: '3'
services: 
  iot: 
    build: 
      context: ./IoT
      dockerfile: Dockerfile
    environment: 
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on: 
      - production-broker
  
  conveyor-belts: 
    build: 
      context: ./ConveyorBelts
      dockerfile: Dockerfile
    environment: 
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on: 
      - production-broker
    
  production-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 