version: "3"
services:
  iot:
    image: ghcr.io/msc-in-software-engineering/python_iot_pub:latest
    environment:
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - production-broker

  conveyor-belts:
    image: ghcr.io/msc-in-software-engineering/python_conveyor_belts_pub:latest
    environment:
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - production-broker

  robotics:
    image: ghcr.io/msc-in-software-engineering/python_robotics_pub:latest
    environment:
      - MQTT_BROKER_ADDRESS=production-broker
    depends_on:
      - production-broker

  production-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
