FROM mcr.microsoft.com/dotnet/sdk:6.0 
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore 
COPY . ./
RUN dotnet add package Confluent.Kafka
RUN dotnet build

# environment variables for MongoDB connection
ENV MONGODB_HOST="mongodb"
ENV MONGODB_PORT="27017"
ENV MONGODB_DATABASE="brickmonitoringdb"
ENV MONGODB_USERNAME="user"
ENV MONGODB_PASSWORD="password"

CMD ["dotnet", "run"]